name: opt
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - gffread
  - bowtie2
  - samtools
  - pip:
      - streamlit>=1.32
      - pysam
      - numpy==1.24
      - scipy
      - matplotlib
      - scikit-learn
      - scprep
      - pandas
      - biopython
      - pyfastx
      - requests
      - setuptools
      - .
